### ISSUE TITLE
Error Kazakh Letters

### ISSUE THREAD

**Issue by brkrtp** [pr0gramista/charset_converter#28]
Hi i cant flutter esc pos print Kazakh Letters.

` printer.rawBytes(await CharsetConverter.encode(codeTable, "Круассан с шоколадом "));`

`  esc_pos_printer: ^4.1.0
  charset_converter: ^2.1.1
  esc_pos_utils: ^1.1.0`

`[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(encoding_failed, Encoding failed, reason unknown, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:315:18)
<asynchronous suspension>
#2      CharsetConverter.encode (package:charset_converter/charset_converter.dart:19:20)
<asynchronous suspension>
#3      _WebViewExampleState.printDemoReceipt (package:my_app/main.dart:967:24)
`

**Comment by zhake555** [comment]
value of codeTable?

**Comment by TamirlanBir** [comment]
Did u solve that problem ?

**Comment by zhake555** [comment]
> Did u solve that problem ?

тек орысша әріптер, қазақша шығара алмадым әзірге
