### ISSUE TITLE
Hi i cant flutter esc pos print Kazakh Letters.

### ISSUE THREAD

**Issue by TamirlanBir** [pr0gramista/charset_converter#31]
Hi i cant flutter esc pos print Kazakh Letters.
```
Uint8List cash =
        await CharsetConverter.encode(encodPrint, "Қолма-қол ақша салу");

 print_bluetooth_thermal: ^1.0.9  charset_converter: ^2.1.1  esc_pos_utils_plus: ^2.0.2

 Unhandled Exception: PlatformException(encoding_failed, Encoding failed, reason unknown, null, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:652:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:310:18)
<asynchronous suspension>
#2      CharsetConverter.encode (package:charset_converter/charset_converter.dart:19:20)
<asynchronous suspension>
```

**Comment by pr0gramista** [comment]
Hi, thanks for reporting the issue.
What code page name did you try to encode with? And also is the issue with particular characters or with any?

**Comment by TamirlanBir** [comment]
Hi, I use parts CP866 and cp1251, and the error in the frequency of Kazakh letters ('ә', 'ғ', 'қ', 'ң', 'ө', 'ұ', 'ү', 'һ', 'і')

**Comment by TamirlanBir** [comment]
> Ah, I see. There is a Kazakh variant of CP1251, where those letters appear. Could you try to use `KZ-1048` or its aliases `STRK1048-2002`, `RK1048`?

Doesn't work( There is the list of codePages , and there only `RK1048`

**Comment by TamirlanBir** [comment]
@pr0gramista 
hello! any news?

**Comment by pr0gramista** [comment]
Hi, I am afraid I have none. 

The package itself isn't providing any code pages, instead it is handled by calls to underlying libraries, which I have no control of.

Perhaps you can write a necessary code page yourself. Not sure how Kazakh language is represented, but it might be as simple as mapping bytes from a table of codes.
